server:
  port: ${PORT:8080}

spring:
  application:
    name: filalivre
  datasource:
    url: jdbc:sqlite:${FILALIVRE_DB_PATH:../database/filalivre.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
  web:
    resources:
      static-locations: classpath:/static/, file:${FILALIVRE_FRONTEND_PATH:../frontend}/
  mvc:
    throw-exception-if-no-handler-found: true

filalivre:
  versao: 1.0.0
